GET http://localhost:8080/store/order/add?ids=1001&ids=1002
###
GET http://localhost:8080/store/order/add?ids=1003
###
GET http://localhost:8080/store/order/add?ids=1004
###
GET http://localhost:8080/store/order/get
###